### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by MohamedNedal** [jgieseler/Solar-MACH#13]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://share.streamlit.io/jgieseler/solar-mach) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by jgieseler** [comment]
@MohamedNedal Thanks for the info! Don't know if you were part of it, but we just had a presentation at ESA's [PyHC summer school](https://heliopython.org/summer-school), and it seems the ~100 participants accessing the Streamlit app at the same time was a bit too much. :sweat_smile:
