### ISSUE TITLE
Citation box appears twice in the main screen of the app

### ISSUE THREAD

**Issue by AthKouloumvakos** [jgieseler/Solar-MACH#25]
The citation box appears twice in the main screen of the app because there are two instances in the .app

One of the two, prepferably the top one (so some of the space be released and the plot to appear first), can be removed.

**Comment by jgieseler** [comment]
Thanks for noticing! Funny, I moved the citation box upwards, but somehow managed to directly add it again in the original bottom position. And this was already 8 months ago. :sweat_smile: 

I put it below the plot for now. I agree, it's better to have the plot visible directly, but the citation info is still rather new, so I'd like to have it not buried in the footnote.
