### ISSUE TITLE
Please loosen matplotlib requirement

### ISSUE THREAD

**Issue by sapols** [jgieseler/Solar-MACH#27]
Solarmach currently has a requirement pinning matplotlib to exactly version 3.5.3. We had a discussion with you all about this right before the PyHC Summer School where we learned it's compatible with versions higher than 3.5.3. Will you please loosen this requirement? Maybe change it to a lower bound, like `matplotlib>=3.5.3`? Whatever makes most sense for this package.

This has become an issue for the [PyHC environment](https://github.com/heliophysicsPy/pyhc-docker-environment). Solarmach forces us to install 3.5.3 which is too low of a version for some other PyHC packages (e.g. pySPEDAS which requires matplotlib>=3.6.2).

Please and thank you!

**Comment by jgieseler** [comment]
Fixed with https://github.com/jgieseler/solarmach/releases/tag/v0.4.0

(This repo is only for the Streamlit part used for https://solar-mach.github.io)
