### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by zheyiding96** [jgieseler/Solar-MACH#30]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://solar-mach.streamlit.app/jgieseler/solar-mach/main) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by jgieseler** [comment]
Thanks a lot for the notification! I deactivated the additional package streamlit_analytics2, which seems to have some problems with the most recent streamlit version, and rebooted the app. Everything should now work again. 👍
